#!/bin/bash
# Script author: MrVaykadji http://askubuntu.com/users/176689/mrvaykadji
# Modified by Andrew <andrew@webupd8.org>:
#  - use the NodeJS PPA to avoid build failure with grunt-cli
#  - use the Popcorn Time icon
#  - added check for apt, dpkg, etc.
#  - added some checks when creating symbolic links
#  - added video playback work-around for Ubuntu 32bit 

function checkAPT()
{
sleep 1
for lock in synaptic update-manager software-center apt-get "dpkg " aptitude
do
 if ps -U root -u root u | grep "$lock" | grep -v grep > /dev/null; then 
  echo "Installation won't work. Please close $lock first then try again.";
  exit
 fi
done
}

#information
echo "
Popcorn-Time Beta 2 for Ubuntu-Linux
------------------------------------
WARNING: Popcorn Time streams movies from Torrents. Downloading copyrighted material may be illegal in your country. Use at your own risk.
"

#verify awareness
read -p "Do you wish to install Popcorn Time [y/n] ? "
if [ "$REPLY" == "y" ] ; then
 sudo echo -e "\nThis may take a while...\n"
else
 exit 0
fi

#dependencies install
checkAPT
echo "- Installing dependencies from repositories..."
sudo add-apt-repository -y ppa:chris-lea/node.js
sudo apt-get update 
sudo apt-get install nodejs git wget -y && echo -e "...Ok.\n"

#npm install for CLI
echo "- Installing CLI from 'npm'..."
sudo npm install -g grunt-cli && echo -e "...Ok.\n"

#git clone
echo "- Cloning GITHUB repository..."
git clone https://github.com/cettox/popcorn-app.git && echo -e "...Ok.\n"

#configure
cd popcorn-app/
    #check architecture
    if [ -n "`arch | grep 64`" ] ; then
        #64bits
        ARCH=linux64
    else
        #32bits
        ARCH=linux32
        sed -i 's/linux32: false/linux32: true/g' Gruntfile.js
        sed -i 's/linux64: true/linux64: false/g' Gruntfile.js
    fi
    sed -i 's/mac: true/mac: false/g' Gruntfile.js
    sed -i 's/win: true/win: false/g' Gruntfile.js

#repair broken npm dependencies
sudo rm package.json 
sudo wget -O package.json https://raw.github.com/jduncanator/popcorn-app/f3e0ab47057238fbd12b8f8dee3f4fcbe0b36254/package.json 

#repair broken nodejs symlink
if [ ! -e /usr/bin/node ]; then
 sudo ln -s /usr/bin/nodejs /usr/bin/node
fi

#install NPM dependencies
echo "- Installing NPM dependencies..."
sudo npm install -g grunt-cli && echo -e "...Ok.\n"
sudo npm install && echo -e "...Ok.\n"

#build with grunt
echo "- Building with 'grunt'..."
sudo grunt nodewkbuild && echo -e "...Ok.\n"

#Copy program into /opt
echo "- Installing Popcorn-Time in '/opt/Popcorn-Time/'"
cd build/releases/Popcorn-Time/$ARCH/
sudo mkdir -p /opt
sudo cp -r Popcorn-Time /opt
sudo chmod +x /opt/Popcorn-Time/Popcorn-Time
sudo rm -f "/usr/bin/popcorn-time"
sudo ln -s /opt/Popcorn-Time/Popcorn-Time /usr/bin/popcorn-time && echo "...Ok.\n"

#fixing libudev
if [ "$ARCH" == "linux64" ] ; then
 if [ ! -e /lib/x86_64-linux-gnu/libudev.so.0 ]; then
  sudo ln -s /lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libudev.so.0
 fi
elif [ "$ARCH" == "linux32" ] ; then
 if [ ! -e /lib/i386-linux-gnu/libudev.so.0 ]; then
  sudo ln -s /lib/i386-linux-gnu/libudev.so.1 /lib/i386-linux-gnu/libudev.so.0
 fi
fi

#fixing playback on 32bit
if [ "$ARCH" == "linux32" ] ; then
 sudo rm -f "/opt/Popcorn-Time/libffmpegsumo.so"
 wget https://github.com/hotice/webupd8/raw/master/libffmpegsumo.so -O /tmp/libffmpegsumo.so
 sudo cp /tmp/libffmpegsumo.so /opt/Popcorn-Time/
fi

#testing app
echo "The application 'Popcorn-Time' will now be tested for 5 secondes.
"
/usr/bin/popcorn-time &
sleep 5
killall Popcorn-Time
read -p "
Did you see the Popcorn-Time application ?
If yes, do you wish to remove all the unecessary files now that the program works [y/n] ? "
if [ "$REPLY" == "y" ] ; then
    #remove building files
    echo "- Removing building files now unwanted..."
    cd ../../../../..
    sudo rm -r popcorn-app && echo -e "...Ok.\n"
fi

#create launcher
echo "- Creating launcher/shortcut in '/usr/share/applications/'..."
wget https://github.com/hotice/webupd8/raw/master/popcorntime.png -O /tmp/popcorntime.png
sudo cp /tmp/popcorntime.png /usr/share/pixmaps/
echo "[Desktop Entry]
Comment=Watch movies in streaming with P2P.
Name=Popcorn Time
Exec=/usr/bin/popcorn-time
StartupNotify=false
Type=Application
Icon=popcorntime" | sudo tee /usr/share/applications/popcorn-time.desktop
sudo chmod +x /usr/share/applications/popcorn-time.desktop && echo -e "...Ok.\n"

echo "
Installation done ! Popcorn-time should be now available through : 
- Dash
- Commandline 'popcorn-time'"

exit 0
